DB: Database connection setup
CyFy-Blockchain/api-gateway pull request #12
Opened 2024-09-30 23:39 UTC by MHA10

- Database connection setup
- Postgres
- Docker
- TypeORM

2024-09-30 23:57 UTC, MHassanTariq requested changes

2024-09-30 23:57 UTC, MHassanTariq commented on README.md
> +npm
npm _install_ to install the dependencies?

2024-09-30 23:57 UTC, MHassanTariq commented on README.md
> +TableName=<name> npm run local-migration:generate
Are you sure that `TableName=<name>` will come in the start of the command?

2024-09-30 23:57 UTC, MHassanTariq commented on package.json
> +    "prod-migration:schema-drop": "NODE_ENV=production ts-node ./node_modules/typeorm/cli.js schema:drop -d ./dist/config/datasource.js",
Can we filter out to keep only the ones we will be needing? For instance, do we need to drop the entire schema at any point? 

Plus, I think making prod-migration and local-migration is clustering the scripts in package.json. What if we use a `.env` variable instead to specify our deployment?

2024-09-30 23:57 UTC, MHassanTariq commented on src/config/ormconfig.ts
> -config();
Removed by mistake? 
We will be needing env variables. No?

2024-10-01 00:03 UTC, MHA10 commented on README.md
> +npm
aaah yes! Not a npm lover so 😛

2024-10-01 00:04 UTC, MHA10 commented on README.md
> +TableName=<name> npm run local-migration:generate
Yup, it works like a charm.

2024-10-01 00:05 UTC, MHA10 commented on package.json
> +    "prod-migration:schema-drop": "NODE_ENV=production ts-node ./node_modules/typeorm/cli.js schema:drop -d ./dist/config/datasource.js",
Yup, we can improve this part here.

2024-10-01 00:05 UTC, MHA10 commented on src/config/ormconfig.ts
> -config();
added Nest config on app level, so no need of it anymore.

2024-10-01 00:07 UTC, MHA10 commented
@MHassanTariq 
I'll improve and clean the package.json commands, then you can review those.

2024-10-01 23:40 UTC, MHassanTariq approved these changes

2024-10-01 23:41 UTC, merged